/**
 * The 80 COCO classes in YOLOX's output order (index = classIndex), with the
 * French names hand-translated so detections read naturally in both UI
 * languages — 80 entries is small enough to own, unlike ImageNet's 1,000.
 */
export const COCO_EN = [
  'person',
  'bicycle',
  'car',
  'motorcycle',
  'airplane',
  'bus',
  'train',
  'truck',
  'boat',
  'traffic light',
  'fire hydrant',
  'stop sign',
  'parking meter',
  'bench',
  'bird',
  'cat',
  'dog',
  'horse',
  'sheep',
  'cow',
  'elephant',
  'bear',
  'zebra',
  'giraffe',
  'backpack',
  'umbrella',
  'handbag',
  'tie',
  'suitcase',
  'frisbee',
  'skis',
  'snowboard',
  'sports ball',
  'kite',
  'baseball bat',
  'baseball glove',
  'skateboard',
  'surfboard',
  'tennis racket',
  'bottle',
  'wine glass',
  'cup',
  'fork',
  'knife',
  'spoon',
  'bowl',
  'banana',
  'apple',
  'sandwich',
  'orange',
  'broccoli',
  'carrot',
  'hot dog',
  'pizza',
  'donut',
  'cake',
  'chair',
  'couch',
  'potted plant',
  'bed',
  'dining table',
  'toilet',
  'tv',
  'laptop',
  'mouse',
  'remote',
  'keyboard',
  'cell phone',
  'microwave',
  'oven',
  'toaster',
  'sink',
  'refrigerator',
  'book',
  'clock',
  'vase',
  'scissors',
  'teddy bear',
  'hair drier',
  'toothbrush',
] as const;

export const COCO_FR = [
  'personne',
  'vélo',
  'voiture',
  'moto',
  'avion',
  'bus',
  'train',
  'camion',
  'bateau',
  'feu de circulation',
  "borne d'incendie",
  'panneau stop',
  'parcomètre',
  'banc',
  'oiseau',
  'chat',
  'chien',
  'cheval',
  'mouton',
  'vache',
  'éléphant',
  'ours',
  'zèbre',
  'girafe',
  'sac à dos',
  'parapluie',
  'sac à main',
  'cravate',
  'valise',
  'frisbee',
  'skis',
  'planche à neige',
  'ballon',
  'cerf-volant',
  'bâton de baseball',
  'gant de baseball',
  'planche à roulettes',
  'planche de surf',
  'raquette de tennis',
  'bouteille',
  'verre à vin',
  'tasse',
  'fourchette',
  'couteau',
  'cuillère',
  'bol',
  'banane',
  'pomme',
  'sandwich',
  'orange',
  'brocoli',
  'carotte',
  'hot-dog',
  'pizza',
  'beigne',
  'gâteau',
  'chaise',
  'canapé',
  'plante en pot',
  'lit',
  'table à manger',
  'toilette',
  'téléviseur',
  'ordinateur portable',
  'souris',
  'télécommande',
  'clavier',
  'cellulaire',
  'micro-ondes',
  'four',
  'grille-pain',
  'évier',
  'réfrigérateur',
  'livre',
  'horloge',
  'vase',
  'ciseaux',
  'ourson en peluche',
  'sèche-cheveux',
  'brosse à dents',
] as const;

export function cocoLabel(index: number, lang: string): string {
  const list = lang.startsWith('fr') ? COCO_FR : COCO_EN;
  return list[index] ?? `#${index}`;
}
